### ISSUE TITLE
get ready for debt market collapse 

### ISSUE THREAD

**Issue by clearwater-trust** [lalanza808/docker-monero-node#10]
Hello.

Thanks for this excellent node monitor. How would I add top block and hash rate data to Graphana dashborard?

Fun, exciting, extra data to monitor.

**Comment by lalanza808** [comment]
I just pushed a new change which contains a more in-depth exporter. It should have those metrics available. The default dashboard has both of those (if I understand you correctly on hash rate metric)

**Comment by clearwater-trust** [comment]
Thank you! I will try the install this weekend.

What is the best way to upgrade the docker image?

wget and rebuild?

**Comment by lalanza808** [comment]
`docker-compose -f docker-compose.yaml build` or `make build` in the repo

**Comment by clearwater-trust** [comment]
Here's my error with new docker image:
monerod_grafana | Failed to start grafana. error: migration failed (id = Add index user.login/user.email): attempt to write a readonly database
monerod_grafana | migration failed (id = Add index user.login/user.email): attempt to write a readonly database

**Comment by lalanza808** [comment]
If you're okay with deleting your existing Grafana (assuming no custom dashboards, users, settings, panels, etc) you can delete the volume and recreate from scratch:

```
docker rm -f monerod_grafana
docker volume rm docker-monero-node_grafana
docker-compose up -d
```

**Comment by clearwater-trust** [comment]
Look at all those sweet sweet graphs. Thanks.
