### ISSUE TITLE
Stats stop refreshing

### ISSUE THREAD

**Issue by woodscode** [lalanza808/docker-monero-node#17]
monerod_exporter | 2023-08-09T20:17:44.665Z     ERROR   collector/collector.go:144      wait    {"error": "transaction_pool collect: fetch data: get transactionpool stats: raw request: submit request: do: Get \"http://monerod:18083/get_transaction_pool_stats\": context deadline exceeded"}

monerod_exporter | 2023-08-09T20:19:54.684Z     ERROR   collector/collector.go:144      wait    {"error": "net collect: fetch data: get netstats: raw request: submit request: do: Get \"http://monerod:18083/get_net_stats\": context deadline exceeded"}

monerod_exporter | 2023-08-09T20:20:14.689Z     ERROR   collector/collector.go:144      wait    {"error": "lastblock collect: fetch last block data: get last block header: jsonrpc: submit request: do: Get \"http://monerod:18083/json_rpc\": context deadline exceeded"}

Seems the exporter is getting these errors over and over again. It was working when I first started to sync the blocks - but now it is failing

![image](https://github.com/lalanza808/docker-monero-node/assets/25874183/c7a05bd7-ae05-413a-a4a6-618ec680d570)

Any help would be greatly appreciated!

**Comment by woodscode** [comment]
I even tried to move the setup to a new server, same issue. One thing to note - the data files for monerod are stored on a USB drive that is mounted on on the server from another server. Not sure if that is an issue, but it was working before. Perhaps the data is too large?

**Comment by clearwater-trust** [comment]
Hello. I recently had same issue on my node while syncing. My server was dangerously **low on resources** and not publishing the stats, however, the node continued to sync. When your node is synchronized, your stats will return.
