### ISSUE TITLE
Great image. Thank you. 

### ISSUE THREAD

**Issue by clearwater-trust** [lalanza808/docker-monero-node#2]
How can I install additional plugins through grafana-cli using this docker image?
I suppose this is more of a docker question? I've tried:
environment variables in .env and docker-compose.yaml GF_INSTALL_PLUGINS=
but i can't get my datasource plugin to show after several docker restart grafana attempts

Thanks for this image.

**Comment by lalanza808** [comment]
Hey, thanks for the feedback!

The method you mentioned is correct - I've added the `GF_INSTALL_PLUGINS` environment variable.

Try instead to `docker-compose down && docker-compose up -d` to hard stop and start Grafana. You should be able to see the plugins get installed in the logs: `docker-compose logs -f grafana`

**Comment by clearwater-trust** [comment]
Thank you. To install additional plugins I added:
.env
GF_INSTALL_PLUGINS=[name of grafana plugin]
docker-compose.yaml
GF_INSTALL_PLUGINS: "${GF_INSTALL_PLUGINS}"

and then the hard stop and start Grafana

**Comment by lalanza808** [comment]
That's it, nice work! Thanks for contributing.
