### ISSUE TITLE
Error: connections collect: fetch data: get connections

### ISSUE THREAD

**Issue by hundehausen** [lalanza808/docker-monero-node#22]
Since today, I get this error from the exporter:

`ERROR	collector/collector.go:144	wait	{"error": "connections collect: fetch data: get connections: jsonrpc: submit request: decode: invalid character '\\x00' in string literal"}`

I only get half of the data, most things are missing.
![Screenshot 2024-03-08 at 21-22-27 Grafana](https://github.com/lalanza808/docker-monero-node/assets/25672277/069e46e8-a90f-40c2-8ca5-375b5cf56b52)

**Comment by lalanza808** [comment]
does the issue still persist? i am bootstrapping fresh to test...will report back in a day or so

**Comment by hundehausen** [comment]
No, it's not happening anymore. It was when the network activity was very high.

**Comment by hundehausen** [comment]
I have to reopen this issue. With the recent spikes in activity on my node, this happens again.

**Comment by lalanza808** [comment]
the exporter was developed by @ciracosta - not sure if he's still active much or willing to help debug
