### ISSUE TITLE
How give Monero a RPC Username and Password?

### ISSUE THREAD

**Issue by jahway603** [lalanza808/docker-monero-node#6]
How do you give this Monero docker a RPC Username and Password?

**Comment by clearwater-trust** [comment]
In docker-compose.yaml - look under monerod for- command: monerod --rpc-command-here 

This will send commands to monerod when you run docker.

**Comment by jahway603** [comment]
Thank you @clearwater-trust for that. I was able to get it going by removing `--public-node` and adding `--rpc-login` per the [RPC documentation here](https://monerodocs.org/interacting/monerod-reference/) in that section of the docker-compose.yaml.
