### ISSUE TITLE
This repo is not maintained anymore

### ISSUE THREAD

**Issue by jahway603** [lalanza808/docker-monero-node#8]
After making pull requests to keep this repo updated, the maintainer of this repo has not been active and has not submitted any of the submitted changes. This repo has been forked and is still maintained by me here - https://codeberg.org/jahway603/docker-monero-node

**Comment by lalanza808** [comment]
been pretty busy with life lately and I guess github isn't configured to email me on issues/PRs anymore. I'll fix it so I can stay in the loop better.
